default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: music_development

test:
  <<: *default
  database: "test_database"

production:
  <<: *default
  adapter: postgresql
  prepared_statements: false
